#!/usr/bin/env bash

#
# NOTE: This script is run within the chroot after second stage debootstrap!
#

set -e

if [ "$#" -ne 2 ]; then
	echo "Usage: $0 DIST DIST_URL"
	exit 1
fi

DIST=$1
DIST_URL=$2

echo "Running postinstall script..."

insserv usbmount-start
insserv framebuffer-start
insserv hostname-init

# Prevent apt-get from starting services
echo "#!/bin/sh
exit 101
" > /usr/sbin/policy-rc.d
chmod +x /usr/sbin/policy-rc.d

# Run custom install scripts
if [ -d /postinst ]; then
	find /postinst -maxdepth 1 -type f -executable -not -name "*~" -exec {} \;
fi

# Run custom install scripts for a specific distribution
if [ -d /postinst/$DIST ]; then
	find /postinst/$DIST -maxdepth 1 -type f -executable -not -name "*~" -exec {} \;
fi

# Re-enable services to start
rm /usr/sbin/policy-rc.d

# Cleanup
apt-get clean

